### ISSUE TITLE
Tbt.js line 3 

### ISSUE THREAD

**Issue by RIAEvangelist** [kylehulscher/Trial-by-Typing#1]
Just curious, is that CORS safe when deployed on a remote domain instead of locally? Not sure what GitHub's policy is on it.

Cool idea 💡

![toes](https://www.icegif.com/wp-content/uploads/icegif-1851.gif)

**Comment by kylehulscher** [comment]
I can't say for sure if it would be happy from another domain. I did it that way mainly for testing purposes and since it's just a fun little typing test hosted on GitHub pages. For a more official release I would definitely prefer to load it with PHP or something from the host server.

**Comment by RIAEvangelist** [comment]
yeah, on the host server using node, you just do a request, OR... you can fetch it through a free proxy. Nice :)
